@echo off
cd /d C:\Users\LENOVO\Desktop\心元\xinyuan-emo-mate
echo [1/2] Starting Vite dev server...
start "vite" /min node node_modules\vite\bin\vite.js --host 0.0.0.0
echo [2/2] Waiting for Vite then launching Electron...
timeout /t 5 /nobreak >nul
echo Vite should be ready, launching Electron...
node node_modules\.bin\electron.cmd .
