; PlatformIO Project Configuration File
;
; ESP32-S3-CAM 极简音频桥接固件
; 通过USB串口做I2S麦克风/扬声器透明传输

[env:esp32-s3-devkitc-1]
platform = espressif32@~6.7.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_mode = dio
board_build.f_cpu = 240000000L

monitor_speed = 115200
upload_speed = 921600
upload_port = COM5
monitor_port = COM5

; platform_packages removed — toolchain already installed
